version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.x
    commands:
      - npm install
  build:
    commands:
      - npm run build
artifacts:
  files:
    - '**/*'
  base-directory: 'out'
