dev:
	STAGE_NAME=dev RUST_LOG=info cargo lambda watch -P 10000 --package web-lambda-http-api

stg:
	STAGE_NAME=stg RUST_LOG=info cargo lambda watch -P 10000 --package web-lambda-http-api

prod:
	STAGE_NAME=prod RUST_LOG=info cargo lambda watch -P 10000 --package web-lambda-http-api

build:
	cargo lambda build --release --arm64

deploy STAGE_NAME:	build
	cargo lambda deploy --binary-name web-lambda-http-api "{{STAGE_NAME}}-46ki75-web-lambda-function-http_api"
