import type { Metadata } from 'next'
import './globals.scss'

import { Noto_Sans_JP } from 'next/font/google'
import { FirstLoading } from '@/components/FirstLoading'

const notoSansJp = Noto_Sans_JP({
  weight: ['400', '700'],
  subsets: []
})

// TODO: edit metadata
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='ja' className={notoSansJp.className}>
      <body>
        <FirstLoading>{children}</FirstLoading>
      </body>
    </html>
  )
}
