[package]
name = "http-api"
version = "0.1.0"
edition = "2024"

[dependencies]
async-graphql = "7.0.15"
lambda_http = "0.13.0"
serde = "1.0.219"
serde_json = "1.0.140"
thiserror = "2.0.12"

tokio = { version = "1", features = ["full"] }
