[package]
name = "http-api"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_http = "0.17.0"

tokio = { version = "1", features = ["macros"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.20"
