dev:
	STAGE_NAME=dev AWS_LAMBDA_LOG_LEVEL=debug cargo lambda watch -P 10000

build:
	cargo lambda build --release

deploy STAGE_NAME:	build
	cargo lambda deploy --binary-name http-api "{{STAGE_NAME}}-46ki75-web-lambda-function-http_api"