name: packages/web

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    name: Build Test (packages/web-solid)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: jdx/mise-action@v4
        with:
          version: "2026.9.9"
          install_args: "node pnpm"

      - name: Install dependencies
        run: mise run setup:node

      - name: Run Type Check
        run: mise run web:typecheck

      - name: Build and run unit/SSR tests
        run: mise run web:test

  eslint:
    name: Lint (packages/web-solid) - ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: jdx/mise-action@v4
        with:
          version: "2026.9.9"
          install_args: "node pnpm"

      - name: Install dependencies
        run: mise run setup:node

      - name: Run ESLint
        run: mise run web:lint

  stylelint:
    name: Lint (packages/web-solid) - Stylelint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - uses: jdx/mise-action@v4
        with:
          version: "2026.9.9"
          install_args: "node pnpm"

      - name: Install dependencies
        run: mise run setup:node

      - name: Run Stylelint
        run: mise run web:lint:css
