name: Lint (packages/web)

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  eslint:
    name: Lint (packages/web) - ESLint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        id: set-node-version
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
        working-directory: packages/web

      - name: Run ESLint
        run: pnpm run lint
        working-directory: packages/web

  stylelint:
    name: Lint (packages/web) - Stylelint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        id: set-node-version
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          registry-url: "https://registry.npmjs.org"
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install
        working-directory: packages/web

      - name: Run Stylelint
        run: pnpm run stylelint
        working-directory: packages/web
